---
# ! Check the policies here https://github.com/widdix/aws-cf-templates/blob/master/state/s3.yaml
AWSTemplateFormatVersion: 2010-09-09
Description: Create the initial buckets

Parameters:
    deployBucketName:
        Type: String
    cdnBucketName:
        Type: String

Resources:
    ServerlessDeploymentBucket:
        Type: AWS::S3::Bucket
        Properties:
            BucketName: !Ref deployBucketName
            BucketEncryption:
                ServerSideEncryptionConfiguration:
                    - ServerSideEncryptionByDefault:
                          SSEAlgorithm: AES256
            PublicAccessBlockConfiguration:
                BlockPublicAcls: true
                BlockPublicPolicy: true
                IgnorePublicAcls: true
                RestrictPublicBuckets: true

    ServerlessDeploymentBucketPolicy:
        Type: AWS::S3::BucketPolicy
        Properties:
            Bucket: !Ref ServerlessDeploymentBucket
            PolicyDocument:
                Statement:
                    - Action:
                          - "s3:*"
                      Condition:
                          Bool:
                              aws:SecureTransport: false
                      Effect: "Deny"
                      Principal: "*"
                      Resource: !Sub "arn:${AWS::Partition}:s3:::${ServerlessDeploymentBucket}/*"

    CDNBucket:
        Type: AWS::S3::Bucket
        Description: Packs bucket that contains serverless templates
        Properties:
            BucketName: !Ref cdnBucketName
            PublicAccessBlockConfiguration:
                BlockPublicAcls: false
                BlockPublicPolicy: false
                IgnorePublicAcls: false
                RestrictPublicBuckets: false
            BucketEncryption:
                ServerSideEncryptionConfiguration:
                    - ServerSideEncryptionByDefault:
                          SSEAlgorithm: AES256
            CorsConfiguration:
                CorsRules:
                    # https://gist.github.com/simonw/3cbb3a787ce218d9bcf6a4650b0bae36
                    - AllowedOrigins:
                          - "*"
                      AllowedMethods:
                          - HEAD
                          - GET
                          - PUT
                          - POST
                          - DELETE
                      MaxAge: 3000
                      ExposedHeaders:
                          - x-amz-server-side-encryption
                          - x-amz-request-id
                          - x-amz-id-2
                          - ETag
                      AllowedHeaders:
                          - "*"

    CDNBucketPolicy:
        Type: AWS::S3::BucketPolicy
        Properties:
            Bucket: !Ref CDNBucket
            PolicyDocument:
                Statement:
                    - Action:
                          - s3:GetObject
                          - s3:PutObject
                          - s3:DeleteObject
                      Resource: !Sub "arn:${AWS::Partition}:s3:::${CDNBucket}/*"
                      Effect: Allow
                      Principal: "*"

Outputs:
    BucketName:
        Value: !Ref ServerlessDeploymentBucket
        Export:
            Name: !Sub "${deployBucketName}-BucketName"
    BucketArn:
        Description: Arn for accessing packsBucket
        Value: !GetAtt ServerlessDeploymentBucket.Arn
        Export:
            Name: !Sub "${deployBucketName}-BucketArn"
    BucketUrl:
        Description: Url for accessing api bucket
        Value: !Sub https://${ServerlessDeploymentBucket}.s3-${AWS::Region}.amazonaws.com
        Export:
            Name: !Sub "${deployBucketName}-BucketUrl"
